Annik19
LangeHenrik/SDU-ITI-F19 pull request #61
Opened 2019-03-19 23:23 UTC by andrianiKo

2019-03-20 08:36 UTC, jacksgt requested changes
Nice website design!

2019-03-20 08:36 UTC, jacksgt commented on annik19/Images.php
> +    <?php } ?>
Is it correct that both the Login as well as the Logout link point to the `Login.php` page?

2019-03-20 08:36 UTC, jacksgt commented on annik19/Images.php
> +        $stmt = $conn->prepare($user_data);
Since you are using a prepared statement already, you should also bind the `user` parameter to the statement to avoid SQL injections.

```
$sql = "INSERT INTO MyGuests (firstname, lastname, email) VALUES (?, ?, ?)";
$stmt = $conn->prepare($sql);
$stmt->bind_param("sss", $firstname, $lastname, $email);
```

https://www.w3schools.com/php/php_mysql_prepared_statements.asp

2019-03-20 08:36 UTC, jacksgt commented on annik19/Login.php
> +        $stmt = $conn -> prepare($sql);
Again, bind the parameters to the statement to avoid SQL injection.

2019-03-20 08:36 UTC, jacksgt commented on annik19/Register.php
> +        $stmt -> execute();
:+1:

2019-03-20 08:36 UTC, jacksgt commented on annik19/Users.php
> +            </tr>
Just to be sure, you might want to use `htmlspecialchars` here to avoid any XSS (the values in the database are provided by the user, so you can never be sure).

http://php.net/manual/en/function.htmlspecialchars.php

2019-03-20 08:36 UTC, jacksgt commented on annik19/delete.php
> +$stmt -> execute();
Bind parameter to statement.

2019-03-20 08:36 UTC, jacksgt commented on annik19/delete.php
> +$stmt -> execute();
Also, you need to check whether the image exists in the database.
Otherwise the user can send an arbitrary string as 'image_path' and delete any file on the server!

2019-03-20 08:36 UTC, jacksgt commented on annik19/upload.php
> +$stmt = $conn -> prepare($find_user_id);
Bind parameter to prepared statement.

2019-03-20 08:36 UTC, jacksgt commented on annik19/upload.php
> +    $stmt -> execute(); ?>
:+1:

2019-03-22 09:17 UTC, andrianiKo commented on annik19/Users.php
> +            </tr>
changed!

2019-03-22 15:55 UTC, jacksgt approved these changes
Looks good, let's get that merged!

2019-03-23 19:58 UTC, LangeHenrik approved these changes

2019-03-23 19:58 UTC, merged